### ISSUE TITLE
Division by zero error when creating credit memos with no CoD

### ISSUE THREAD

**Issue by dakira** [PHOENIX-MEDIA/Magento2-CashOnDelivery#3]
The CreditMemo.php of all active payment methods seems to get called when trying to create a credit memo regardless of the payment method used on that order.

This leads to many division by zero errors. Here's the relevant part of the stacktrace:

```
Exception #0 (Exception): Warning: Division by zero in /var/www/magento/vendor/phoenix/module-cashondelivery/Model/Total/Creditmemo.php on line 88
#0 /var/www/magento/vendor/phoenix/module-cashondelivery/Model/Total/Creditmemo.php(90): Magento\Framework\App\ErrorHandler->handler(2, 'Division by zer...', '/var/www/magento...', 88, Array)
#1 /var/www/magento/vendor/phoenix/module-cashondelivery/Model/Total/Creditmemo.php(64): Phoenix\CashOnDelivery\Model\Total\Creditmemo->setCustomRefund(Object(Magento\Sales\Model\Order\Creditmemo))
#2 /var/www/magento/vendor/magento/module-sales/Model/Order/Creditmemo.php(337): Phoenix\CashOnDelivery\Model\Total\Creditmemo->collect(Object(Magento\Sales\Model\Order\Creditmemo))
#3 /var/www/magento/vendor/magento/module-sales/Model/Order/CreditmemoFactory.php(79): Magento\Sales\Model\Order\Creditmemo->collectTotals()
#4 /var/www/magento/vendor/magento/module-sales/Controller/Adminhtml/Order/CreditmemoLoader.php(211): Magento\Sales\Model\Order\CreditmemoFactory->createByOrder(Object(Magento\Sales\Model\Order\Interceptor), Array)
#5 /var/www/magento/vendor/magento/module-sales/Controller/Adminhtml/Order/Creditmemo/NewAction.php(63): Magento\Sales\Controller\Adminhtml\Order\CreditmemoLoader->load()
```

**Comment by dakira** [comment]
It looks like this issue was fixed in this commit https://github.com/PHOENIX-MEDIA/Magento2-CashOnDelivery/commit/25009f385538cdd1adfcd79e00bdb2111ebdd64f

But that's not the version I get through composer require as per your instructions.

**Comment by PHOENIX-MEDIA** [comment]
See #4.
